create extension if not exists "hypopg" with schema "extensions";

create extension if not exists "index_advisor" with schema "extensions";

create extension if not exists "postgis" with schema "public";


  create table "public"."places" (
    "created_at" timestamp with time zone not null default timezone('gmt'::text, now()),
    "place_name" text,
    "primary_type" text,
    "other_types" text[],
    "hashed_google_id" text,
    "place_id" bigint generated by default as identity not null
      );


alter table "public"."places" enable row level security;

alter table "public"."diary_completed" add column "cluster_duration_s" integer;

alter table "public"."diary_completed" add column "entry_ids" text[];

alter table "public"."diary_completed" add column "other_types" text[];

alter table "public"."diary_completed" add column "ping_count" integer;

alter table "public"."diary_completed" add column "visit_confidence" text;

alter table "public"."diary_completed" add column "visit_id" text;

alter table "public"."diary_completed" alter column "confirmed_activity" drop not null;

alter table "public"."diary_completed" alter column "confirmed_place" drop not null;

CREATE UNIQUE INDEX diary_completed_visit_unique ON public.diary_completed USING btree (visit_id, deviceid, diary_date);

CREATE INDEX places_hashed_id_idx ON public.places USING btree (hashed_google_id);

CREATE UNIQUE INDEX places_pkey ON public.places USING btree (place_id);

CREATE UNIQUE INDEX places_place_id_key ON public.places USING btree (place_id);

alter table "public"."places" add constraint "places_pkey" PRIMARY KEY using index "places_pkey";

alter table "public"."diary_completed" add constraint "diary_completed_visit_unique" UNIQUE using index "diary_completed_visit_unique";

alter table "public"."places" add constraint "places_place_id_key" UNIQUE using index "places_place_id_key";

grant delete on table "public"."places" to "anon";

grant insert on table "public"."places" to "anon";

grant references on table "public"."places" to "anon";

grant select on table "public"."places" to "anon";

grant trigger on table "public"."places" to "anon";

grant truncate on table "public"."places" to "anon";

grant update on table "public"."places" to "anon";

grant delete on table "public"."places" to "authenticated";

grant insert on table "public"."places" to "authenticated";

grant references on table "public"."places" to "authenticated";

grant select on table "public"."places" to "authenticated";

grant trigger on table "public"."places" to "authenticated";

grant truncate on table "public"."places" to "authenticated";

grant update on table "public"."places" to "authenticated";

grant delete on table "public"."places" to "service_role";

grant insert on table "public"."places" to "service_role";

grant references on table "public"."places" to "service_role";

grant select on table "public"."places" to "service_role";

grant trigger on table "public"."places" to "service_role";

grant truncate on table "public"."places" to "service_role";

grant update on table "public"."places" to "service_role";



  create policy "Allow anonymous selects"
  on "public"."diary_completed"
  as permissive
  for select
  to authenticated, anon, service_role
using (true);



  create policy "Allow anonymous updates"
  on "public"."diary_completed"
  as permissive
  for update
  to authenticated, anon, service_role
using (true)
with check (true);



  create policy "Write to place table"
  on "public"."places"
  as permissive
  for insert
  to public
with check (true);

